sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

script: 
  - sbt ++$TRAVIS_SCALA_VERSION clean test

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm

scala:
  - 2.11.7

jdk:
  - oraclejdk8

notifications:
  email:
    - igorkurylenko@gmail.com
    - zergoodsound@gmail.com
